### ISSUE TITLE
parsing of formated tables fails in Dokuwiki 2024-02-06 "Kaos"

### ISSUE THREAD

**Issue by tobiasd** [dokuwiki/dokuwiki#4186] opened 2024-02-06 15:09 UTC
After updating to 2024-02-06 "Kaos" pages containing formatted tables (aligned cells, and cell spans) failed to render.

Messages in the logs

```
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "colspan" /inc/parserutils.php(535)
```

and

```
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "table_align" /inc/parserutils.php(535)
```

PHP version is 8.0.30

removing the formatting of the tables in the page source txt files made the rendering of the pages work again.

**Comment by splitbrain** [comment] 2024-02-06 15:23
I cannot reproduce this. https://www.dokuwiki.org/wiki:syntax#tables seems to render fine.

colspan and table_align instructions should be merged into cell parameters in [finalizeTable](https://github.com/dokuwiki/dokuwiki/blob/master/inc/Parsing/Handler/Table.php#L146) and never reach any renderer...

Can you share the syntax of a table that causes this issue for you?

**Comment by michitux** [comment] 2024-02-06 15:51
Is this possibly an issue with the instruction cache not being invalidated during/after the upgrade? Do you still get an issue when viewing the previous version of the page?

**Comment by fiwswe** [comment] 2024-02-06 16:04
Would adding the `purge=true` URL parameter invalidate the instruction cache to help verify if this is indeed the cause?

**Comment by Klap-in** [comment] 2024-02-06 18:14
> Would adding the `purge=true` URL parameter invalidate the instruction cache to help verify if this is indeed the cause?

This work indeed for one page. 
If caches are not expired after upgrade, which does sound logic because some PHP files are also a dependency of the caches, it is probably handiest to re-save the Configuration Manager, because that expires all caches.

**Comment by tobiasd** [comment] 2024-02-06 18:50
> Can you share the syntax of a table that causes this issue for you?

I can provide you with some files that did not render 
[DW-table-alignment-errors.tar.gz](https://github.com/dokuwiki/dokuwiki/files/14184836/DW-table-alignment-errors.tar.gz). One problem was cells combined with `| bla ||| blubb |`  and some alignements `^  bla  ^      blubb ^|` with multible spaces so that the tables are properly aligned in the source of the text as well.

**Comment by tobiasd** [comment] 2024-02-06 18:52
> Do you still get an issue when viewing the previous version of the page?



> Is this possibly an issue with the instruction cache not being invalidated during/after the upgrade? Do you still get an issue when viewing the previous version of the page?

No old versions of the page are shown.

**Comment by StarArmy** [comment] 2024-02-07 03:43
Okay, this broke pages on my wiki too and I was able to figure out that this happens when there's a table that has an uneven number of columns, like if someone forgot a cell and the cell counts are like 4, 3, 4.

**Comment by splitbrain** [comment] 2024-02-07 07:53
In this [post](https://forum.dokuwiki.org/d/21997-after-kaos-update-error-message-occurs-with-certain-tables/5) @StarArmy  suggests that the following code reproduces the error:

```
|   Name           ^ Race            ^ type          ^ Relationship^
^ [[characters:galactic_horizon:iriss_zepheris]]      |   Separa'shan                |  created       |
^ [[characters:yamatai:itatski_sachiko]]     | Nekovakyrja           |  Born     | Taken  |
```

However I still cannot reproduce it: https://www.dokuwiki.org/playground:tableproblem

**Comment by LMS235** [comment] 2024-02-07 14:57
can now confirm the function. Have also run into the error "does not have a method "table_align"". Have now installed the fix manually, works again

**Comment by TJuberg** [comment] 2024-02-07 15:36
Can also confirm the fix solves the issue for us.

**Comment by tobiasd** [comment] 2024-02-07 19:47
I applied the fix and used an old version of one of the files that did not render before and it works now :+1:

**Closed** 2024-02-09 10:12 UTC

**Comment by jlpoolen** [comment] 2024-02-09 18:00
I encountered the same problem and I applied the patch by hand editing: remming 2 code lines, 173 & 178, and adding 2 code lines, 179 & 180, and the problem still manifests itself:

`
Fix: https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d
I applied the patch to 
inc/Parsing/Handler/Table.php
 /var/www/localhost/htdocs/dokuwiki/inc/Parsing/Handler/Table.php


173 //jlpoole        $counter = count($this->tableCalls);
174
175         // Look for the colspan elements and increment the colspan on the
176         // previous non-empty opening cell. Once done, delete all the cells
177         // that contain colspans
178 //jlpoole        for ($key = 0; $key < $counter; ++$key) {
179          $key = -1;
180          while (++$key < count($this->tableCalls)) {

Stopped then started Apache.
Error on screen: 
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "colspan"

An unforeseen error has occured. This is most likely a bug somewhere.

More info has been written to the DokuWiki error log.

From: /var/www/localhost/htdocs/dokuwiki/data/log/error/2024-02-09.log

        2024-02-09 17:48:05     /var/www/localhost/htdocs/dokuwiki/inc/parserutils.php(535)     TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "colspan"
          #0 /var/www/localhost/htdocs/dokuwiki/inc/parserutils.php(299): p_render_metadata()
          #1 /var/www/localhost/htdocs/dokuwiki/inc/common.php(262): p_get_metadata()
          #2 /var/www/localhost/htdocs/dokuwiki/doku.php(101): pageinfo()
          #3 {main}
        2024-02-09 17:48:59     /var/www/localhost/htdocs/dokuwiki/inc/parserutils.php(535)     TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "colspan"
          #0 /var/www/localhost/htdocs/dokuwiki/inc/parserutils.php(299): p_render_metadata()
          #1 /var/www/localhost/htdocs/dokuwiki/inc/common.php(262): p_get_metadata()
          #2 /var/www/localhost/htdocs/dokuwiki/doku.php(101): pageinfo()
          #3 {main}

`
This page worked fine before I upgraded to "Kaos."

**Comment by jlpoolen** [comment] 2024-02-09 18:10
I found the problem:  I had two header delimiters without anything in between:
Example which triggers error:

`^Unit Name ^ Address ^Contact ^Email ^Telephone ^Longitude ^ Latitude ^Elevation ^Site Description^Wifi SSID^^ZeroTier IP^`

Example - **Fixed**:
`^Unit Name ^ Address ^Contact ^Email ^Telephone ^Longitude ^ Latitude ^Elevation ^Site Description^Wifi SSID^ZeroTier IP^`

I went into my source and replaced a double caret, "^^", with a single caret, "^", and now the page renders.

**Comment by fiwswe** [comment] 2024-02-09 18:30
a) You did not actually apply the patch, you tried to implement something similar.

b) Restarting Apache httpd is not required. Even restarting your PHP-FPM process is not required if you are using that.

c) Two table header delimiters `^^` are perfectly valid syntax. They cause a header cell to span two columns. And they work just fine for me. E.g.:
<img width="864" alt="Image 2024-02-09 19 27 36" src="https://github.com/dokuwiki/dokuwiki/assets/53953985/c14229a9-0d5f-4d86-bbb8-9b7376726662">

d) Since your modification didn't work whereas others (including myself) confirmed  https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d to solve the issue there remain two possibilities:
* You did something wrong.
* You encountered a different issue.

I'd start by applying https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d exactly instead of approximating what it does.

**Comment by jlpoolen** [comment] 2024-02-09 18:58
> a) You did not actually apply the patch, you tried to implement something similar.
> 
> b) Restarting Apache httpd is not required. Even restarting your PHP-FPM process is not required if you are using that.
> 
> c) Two table header delimiters `^^` are perfectly valid syntax. They cause a header cell to span two columns. And they work just fine for me. E.g.: <img alt="Image 2024-02-09 19 27 36" width="864" src="https://private-user-images.githubusercontent.com/53953985/303742559-c14229a9-0d5f-4d86-bbb8-9b7376726662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDM3NTksIm5iZiI6MTcwNzUwMzQ1OSwicGF0aCI6Ii81Mzk1Mzk4NS8zMDM3NDI1NTktYzE0MjI5YTktMGQ1Zi00ZDg2LWJiYjgtOWI3Mzc2NzI2NjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE4MzA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODY2MmUyODkwZjQ5ZWJhZmQxZWMyMDJlYzQ0OWQwZmRlMDRhNzY1YmYxNmRlZTExNWNkYTI0MmNkZWM4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZCHoy0wMlKMwlvFLsSKt57TmreOq-uhWfz7g5XtLEU">
> 
> d) Since your modification didn't work whereas others (including myself) confirmed [643ea3a](https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d) to solve the issue there remain two possibilities:
> 
>     * You did something wrong.
> 
>     * You encountered a different issue.
> 
> 
> I'd start by applying [643ea3a](https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d) exactly instead of approximating what it does.

Alas, I do not know how to "patch" in this project.  I think this is the first time I've dived into Dokuwiki's code, I've been using Dokuwiki for over 7 years now.  I hasten to add that _the page with two carets is now properly displaying_ with the hand-edited modification.  I'll spend 5-10 minutes searching for the recommended procedure on "patching" an installed instance, let us hope I find it, otherwise I'm in a works-for-me mode.

**Comment by fiwswe** [comment] 2024-02-09 19:13
Start out with a clean copy of the file, then delete the lines marked red and add the lines marked green in:
https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d#diff-9c184c2835cec4521752da9ebb3ae60f7d78540c10de7792eacbb28d8ca44f73

Or go [here](https://github.com/dokuwiki/dokuwiki/blob/master/inc/Parsing/Handler/Table.php) and download the complete patched file.

At the very least the result will then be equivalent down to the actual line numbers with what others have. That makes diagnosing further problems easier if there are any.

**Comment by fkrauthan** [comment] 2024-02-09 19:13
Any idea when this fix might be released as an actual update?

**Comment by jlpoolen** [comment] 2024-02-09 19:25
> Start out with a clean copy of the file, then delete the lines marked red and add the lines marked green in: [643ea3a#diff-9c184c2835cec4521752da9ebb3ae60f7d78540c10de7792eacbb28d8ca44f73](https://github.com/dokuwiki/dokuwiki/commit/643ea3a6eaa27d23e64c1e9e0bac118f6174594d#diff-9c184c2835cec4521752da9ebb3ae60f7d78540c10de7792eacbb28d8ca44f73)
> 
> Or go [here](https://github.com/dokuwiki/dokuwiki/blob/master/inc/Parsing/Handler/Table.php) and download the complete patched file.
> 
> At the very least the result will then be equivalent down to the actual line numbers with what others have. That makes diagnosing further problems easier if there are any.

Thank you, that was helpful.  Here's what I did to "patch":

```
ares /var/www/localhost/htdocs/dokuwiki # cd /tmp
ares /tmp # wget https://github.com/dokuwiki/dokuwiki/blob/master/inc/Parsing/Handler/Table.php
--2024-02-09 11:15:36--  https://github.com/dokuwiki/dokuwiki/blob/master/inc/Parsing/Handler/Table.php
Resolving github.com... 192.30.255.112
Connecting to github.com|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78546 (77K) [text/plain]
Saving to: ‘Table.php’

Table.php                     100%[=================================================>]  76.71K  --.-KB/s    in 0.04s

2024-02-09 11:15:40 (2.13 MB/s) - ‘Table.php’ saved [78546/78546]

ares /tmp # ls /var/www/localhost/htdocs/dokuwiki/inc/Parsing/Handler/Table.php
/var/www/localhost/htdocs/dokuwiki/inc/Parsing/Handler/Table.php
ares /tmp # mv Table.php /var/www/localhost/htdocs/dokuwiki/inc/Parsing/Handler/Table.php
ares /tmp #
```
I did search Dokuwiki's site and did not find anything such as the above steps I undertook which I think is a succinct method of patching.  I did find a patch plugin that is old and unsupported -- the creator died in 2012.   The unstated step for the sequence above is that I take the output of the "ls" and copy into my clipboard and then paste it to make sure I have the correct path for the "mv" command.  Knowing the URL which you graciously provided where the patched file exists is critical to allowing me to easily download it and then apply to my instance.

The page renders fine now, too.

Thank you.

**Comment by fiwswe** [comment] 2024-02-09 19:32
>Any idea when this fix might be released as an actual update?

No. My guess would be: in the next few weeks.

Meanwhile you can either manually apply cherry picked patches or download and install the [Development Snapshot](http://github.com/splitbrain/dokuwiki/tarball/master), also available from the [DokuWiki download page](https://download.dokuwiki.org). That will contain all merged patches or other changes that happened since the last released version.

**Comment by fiwswe** [comment] 2024-02-11 22:10
@TheRaven500 If you have applied the patch correctly then I'd recommend to go into the [Configuration](https://www.dokuwiki.org/plugin%3Aconfig) and save (without making any changes) to clear the DokuWiki cache.

Please let us know whether that fixes the issue.

**Comment by TheRaven500** [comment] 2024-02-11 22:28
@fiwswe Ha, that worked! Thx! 😎

**Comment by brainsys** [comment] 2024-02-13 11:08
Hi - I.m also having the same issue on an unaltered page from previous version. I replaced Table.php with the new file and did configuration/save as above (throwing in an apache restart for fun) and It clears the error.

But instead of a page I get gibberish starting like this:

payload":{"allShortcutsEnabled":false,"fileTree":{"inc/Parsing/Handler":{"items":[{"name":"AbstractRewriter.php","path":"inc/Parsing/Handler/AbstractRewriter.php","contentType":"file"},{"name":"Block.php","path":"inc/Parsing/Handler/Block.php","contentType":"file"},{"name":"CallWriter.php","path":"inc/Parsing/Handler/CallWriter.php","contentType":"file"},{"name":"CallWriterInterface.php","path":"inc/Parsing/Handler/CallWriterInterface.php","contentType":"file"},{"name":"Lists.php","path":"inc/Parsing/Handler/Lists.php","contentType":"file"},{"name":"Nest.php","path":"inc/Parsing/Handler/Nest.php","contentType":"file"},{"name":"Preformatted.php","path":"inc/Parsing/Handler/Preformatted.php","contentType":"file"},{"name":"Quote.php","path":"inc/Parsing/Handler/Quote.php","contentType":"file"},{"name":"ReWriterInterface.php","path":"inc/Parsing/Handler/ReWriterInterface.php","contentType":"file"},

Any ideas? - Oh and thanks for DokuWiki. Its my complete braindump and constant friend.

**Comment by Klap-in** [comment] 2024-02-13 11:22
The change is in the meantime published as hotfix release. So you can do a upgrade to get the other changes as well.

The output you see is not familiar for me, looks a bit as a file browser? I would guess it is not part of DokuWiki...

**Comment by brainsys** [comment] 2024-02-13 11:30
Yes - that fixed it - thank you!
