### ISSUE TITLE
Kaos update broke user login (authchained/authad, virtualgroup?)

### ISSUE THREAD

**Issue by Meax5qiu** [dokuwiki/dokuwiki#4226] opened 2024-02-26 10:07 UTC
### The problem

Login auth setup: I am using `authchained` with authtypes `"authad:authplain"`, to retrieve authentication from AD first, but with additional local users. This has been working fine so far (since Hogfather times).

Now, I applied the recent update to "Kaos" (via the official upgrade plugin, version 2024-02-06). Login via plain account (with local password) still works, but login with AD credentials broke. On login attempt, an error message appears:

![image](https://github.com/dokuwiki/dokuwiki/assets/104503101/52a1b3d2-1a7e-4809-851d-33c0f65224f6)

> TypeError: Argument 1 passed to str_ends_with() must be of the type string, null given, called in /path/to/dokuwiki/inc/Subscriptions/SubscriberManager.php on line 291
>
> An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the virtualgroup plugin.
>
> More info has been written to the DokuWiki error log.

The error points to the `virtualgroup` plugin. The user with which I have tested login and got the error, is indeed part of virtual groups.

The file that is triggering the error, rather looks like part of the subscription manager (which is active as well).

I had a look into the mentioned file, in particular the `file` function where the error occurs. One difference introduced with Kaos was to replace `substr($id, -1, 1)` with a call to `str_ends_with`. New with PHP 8.0, this function is emulated on PHP 7.4 by `inc/compatibility.php`. But this looks fine either way.

--- 

For now, I had to revert the update (the wiki is in active use). I'd love to contribute to the resolution of this, but it is tricky on a production server. Some time at night, I will retry the update (to retrieve the logs). I'll also modify my AD test user:
* remove it from the virtual groups (authad vs. virtualgroup)
* disable subscriptions (subscriptions)

Any other ideas welcome.

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

7.4.33

### Webserver and version of webserver

Apache 2.4.56 (Debian Bullseye)

### Additional environment information

Relevant/involved plugins:
* authchained
* authad
* virtualgroup

Notifications via e-mail are active

**Comment by splitbrain** [comment] 2024-02-26 10:09
duplicate of #4221

**Closed by splitbrain** 2024-02-26 10:09 UTC
Labels: Bug, duplicate
