### ISSUE TITLE
Very slow search when using the latest release of Dokuwiki - Jack Jackrum

### ISSUE THREAD

**Issue by phobospt** [dokuwiki/dokuwiki#3955] opened 2023-04-14 18:29 UTC
Since upgrading to the lastest release, we are experiencing very slow searches where it takes around 10 seconds for a simple query to return full text results.

A full seearch reindex has been ran but it made no difference, and we have also noticied that the Apache process is taking 100% cpu upon search( like it is it relying on an index) 

The same behaivour is NOT reproducable on the previous version of the Dokuwiki ( 2022-07 ) 

Any ideas?

**Comment by fiwswe** [comment] 2023-05-15 07:27
I can **not** reproduce this on:
DokuWiki 2023-04-04 "Jack Jackrum"
PHP 8.2.6 (via PHP-FPM)
OpenBSD 7.3 amd64 using [httpd(8)](https://man.openbsd.org/httpd.8) running on a VMWare Fusion VM on an older MacBook Pro running macOS 10.12.6.
sprintDoc Template and DokuWiki Template both behave the same in my tests

The search _feels_ like it has the same speed as ever. And I compared to a very similar wiki running 2022-07-31a "Igor" using PHP 7.4.33 on the same host and saw no significant differences.
I do see the php-fpm processes spike on CPU load but that is to expected and it doesn't seem to be excessive — quite in line with a normal wiki page load.

Note: I have not done any testing using Apache httpd or the mod_php Apache extension.

@phobospt Are you experiencing the slowdown with the popup search results that appear when you start typing in the search field? Or after pressing enter and loading the results page?

Note: I think it would be quite hard to figure out a consistent test scenario for measuring search speed. Some of the factors influencing the result are probably:
* Number of wiki pages
* Amount of text on the wiki pages
* Speed of PHP which includes PHP-FPM if applicable, the web server, the host computer, memory, speed of disk access
* Probably the browser
* The search term
* The DokuWiki code involved, i.e. the DW version
* And probably other factors…

### Determining the PHP version
> PHP 8.1.2-1ubuntu2.11 (cli)

The CLI version of PHP is not necessarily the version used by the web server. (For example I have several machines with up to 4 different versions of PHP installed at the same time. I can choose to use any of them for CLI and/or for specific web servers or even for specific paths on a virtual host.)

Also PHP version 8.1.2 seems somewhat dated. [PHP 8.1.19](https://www.php.net/downloads.php#v8.1.19) was recently released. Or better yet, use PHP 8.2.x. (I don't know which versions are readily available for Ubuntu though.)

To determine the actual version of PHP used for the wiki there are several strategies. But be warned that they may have security implications! So generally only enable them for a short test and then disable them again.
1. A very general method would be to place a small PHP script in your DokuWiki root directory. Preferably give the file a name that is hard to guess, e.g. `pmKvYksZPp.php` (choose your own random name) and make its content look something like this:
```php
<?php
echo 'PHP version: '.phpversion().PHP_EOL;
```
Then open `https://<dokuwiki-host>/pmKvYksZPp.php` in a web browser.

2. Enable embedded PHP in your wiki (WARNING! Security implications! Read the warnings!). Pre "Jack Jackrum" you could turn this on with the `phpok` configuration setting. Starting with "Jack Jackrum" you would need a plugin such as [htmlok](https://dokuwiki.org/plugin:htmlok) for that. Then create a wiki page:
```
====== Get the PHP version ======

~~NOCACHE~~
PHP version: <php>echo phpversion();</php>
```

**Comment by fiwswe** [comment] 2023-05-15 11:10
### Addendum:
3. If you are logged into your wiki as an admin you can use the URL parameter `do=check` to see the actual PHP version used for the DokuWiki web server as well as other useful information. I.e. `https://<dokuwiki-host>/?do=check`. Or place a link on a wiki page so you don't need to remember the syntax: `[[this>?do=check|do=check]]`

**Comment by flow-83** [comment] 2023-05-25 14:16
Same issues here till minutes ago. 

I installed `mb_string` extension (first blue message in your do=check picture)

On Ubuntu:
`sudo apt-get install php-mbstring`

**Be aware, service apache2 wants a restart.**

Now DW is fast as usual. 

cheers.

**Comment by fiwswe** [comment] 2023-05-25 16:17
> Maybe `mb_string` should be added to the `system requiements` for an DokuWiki Installation?

Well strictly speaking it is not a _requirement_ as everything works without the extension. It just speeds up certain operations.

So I'd say a recommendation to have this extension should be mentioned. Maybe here: https://www.dokuwiki.org/install:php#extension
I have added some text there to point this out.

**Comment by splitbrain** [comment] 2023-05-25 17:03
@fiwswe thanks for adding it.

Generally mbstring has always been the recommendation and is also checked in the ?do=check action.

I am very surprised about the comments in this thread. To me it seems people here updated PHP when they updated the wiki and simply did not install the same extensions as before. Unfortunately no one above told us about the PHP update and everyone assumed it's DokuWiki related?

Ta least that's the only explanation I have so far, since I really do not see how DokuWiki should behave differently in handling UTF-8 and search between Igor and Jack Jackrum. Nothing should have changed there.

**Comment by Harliff** [comment] 2023-06-05 21:38
Problem solved by `apt install php-mbstring` in debian.

Thanks!

**Comment by phobospt** [comment] 2023-06-26 10:09
Confirmed on my side as well php-mbstring was the missing piece!

**Closed** 2023-08-21 15:03 UTC
