### ISSUE TITLE
class Doku_Renderer_metadata does not have a method "colspan"

### ISSUE THREAD

**Issue by juangacovas** [dokuwiki/dokuwiki#4202] opened 2024-02-10 17:37 UTC
Hello,

Latest dokuwiki version "chaos" left me with an error that does NOT render the rest of the page. The error is:

`TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "colspan"`

I use the following snippet on my index page to display global recent changes (pagelist plugin):

`{{changes>count = 100&maxage = 5184000&render = pagelist&type = edit, minor, create}}`

**Workaround:**
Add the following method to `class Doku_Renderer_metadata` at file `inc/parser/metadata.php`:
```
public function colspan() {
        $this->cdata(DOKU_LF);
}
```
(The error displayed also points it might be an "error" at pagelist plugin).

Hope it helps, I use the wrap plugin and others.

**Comment by Klap-in** [comment] 2024-02-10 18:26
This looks as a duplicate of https://github.com/dokuwiki/dokuwiki/issues/4186

**Comment by fiwswe** [comment] 2024-02-10 18:29
Sounds suspiciously like a duplicate of #4186?

Does PR #4188 fix the issue?

**Closed** 2024-02-12 12:07 UTC
Labels: duplicate
