### ISSUE TITLE
Character rendering issue after "Kratos" upgrade

### ISSUE THREAD

**Issue by eduardomozart** [dokuwiki/dokuwiki#4192] opened 2024-02-07 18:12 UTC
Hello,
I have a page with the following content:

```
====== ArubaOS-CX ======

<code bibtex>
@Comment{refnotes,
  namespace = "harvard"
}
</code>
```

When searching for the following text:

``AOS-CX 10.12 Security Guide @refnotes``

I'm redirected to the page URL: https://wiki.example.com/doku.php?id=refnotes:net:sw:aos-cx&s[]=aos&s[]=cx&s[]=10&s[]=12&s[]=security&s[]=guide

And the ``{`` doesn't seems to be rendered as expected and are shown as ``&#123;``:

<img width="240" alt="image" src="https://github.com/dokuwiki/dokuwiki/assets/2974895/4f2a7501-23c8-4ae4-8b86-6ea70270920f">

But when not searching (https://wiki.example.com/doku.php?id=refnotes:net:sw:aos-cx) it seems to be rendered as expected:

<img width="205" alt="image" src="https://github.com/dokuwiki/dokuwiki/assets/2974895/5a400844-cc9e-432c-8268-d83b803ee350">

I was able to reproduce this problem on another Wiki, so it seems to be a DokuWiki issue, as it doesn't happen on last release.

**Comment by fiwswe** [comment] 2024-02-08 12:31
I can't reproduce this on DokuWiki 2024-02-06 "Kaos". The `<code>` block renders fine including the braces.

(But if you updated to "Kratos" then all bets are off as that version was not released ;-)

Also I don't see what the access method (search or normal page link) would change w.r.t. to the rendering.

Did you try to clear all caches? (Open up the DokuWiki configuration and save without making any changes to clear the DokuWiki cache.)

**Comment by Klap-in** [comment] 2024-02-08 12:39
Search might wrap html tags around results found in the text to highlight them, and sometimes that is interfering with other parts of the layouting. Not sure if that happens here.

**Comment by eduardomozart** [comment] 2024-02-08 13:03
> I can't reproduce this on DokuWiki 2024-02-06 "Kaos". The `<code>` block renders fine including the braces.
> 
> (But if you updated to "Kratos" then all bets are off as that version was not released ;-)
> 
> Also I don't see what the access method (search or normal page link) would change w.r.t. to the rendering.
> 
> Did you try to clear all caches? (Open up the DokuWiki configuration and save without making any changes to clear the DokuWiki cache.)

Hello @fiwswe 
The Kratos was released yesterday, even the Update Manager was updated to update to this release, and there's a lot of issues being related here on Bug Tracker related to this update.
Yes, I cleared the cache. This issue happens only when searching for content and clicking on the result. Did you do that?
The issue happens with the default template and it wasn't happening before upgrading to Kratos.
Thank you for your response.

**Comment by eduardomozart** [comment] 2024-02-08 13:09
> Search might wrap html tags around results found in the text to highlight them, and sometimes that is interfering with other parts of the layouting. Not sure if that happens here.

Hello @Klap-in, I believe so. Maybe some code change broke the search engine. I believe it should parse HTML content before highlighting or showing the result on search, because this kind of issue wasn't happening on DokuWiki old stable. Maybe some security update to handle HTML chars broke the search, but I'm not sure. The PHP server is setup to ``default_charset = UTF-8`` as shown on ``phpinfo()``, so I believe it's not a PHP specific or isolated issue, as I was able to reproduce the issue on another DokuWiki instance.

**Comment by fiwswe** [comment] 2024-02-08 13:19
> The Kratos was released yesterday

I take it, this was meant as a joke?
See: https://www.dokuwiki.org/releasenames, where your misspelling already made the hall of fame ;-)

Yes I also tried to search for the test page and saw no issues.

However I was using the sprintDoc Template.

**Comment by eduardomozart** [comment] 2024-02-08 13:21
That's great, I really love Kratos, like, he brings the Kaos, isn't it? XD

**Comment by eduardomozart** [comment] 2024-02-08 13:23
I was able to reproduce the issue on sprintDoc template too.
<img width="760" alt="image" src="https://github.com/dokuwiki/dokuwiki/assets/2974895/0bd9ff71-9d9c-4649-844e-5713130a89bb">

**Comment by fiwswe** [comment] 2024-02-08 13:41
Here is my result:
<img width="1152" alt="Image 2024-02-08 14 28 40" src="https://github.com/dokuwiki/dokuwiki/assets/53953985/3eb99082-f267-4e6f-a8e6-9cfb25a020ea">
So even the preview in the search results show the brace not the HTML entity.

<img width="868" alt="Image 2024-02-08 14 28 51" src="https://github.com/dokuwiki/dokuwiki/assets/53953985/8e001e8c-55ad-4236-bc0d-a6866aaaf49c">

Could some other non-standard plugin be interfering with the results? Interpreting braces as HTML entities and then literally displaying those entities would take some doing. I doubt this could be accomplished with CSS or even HTML. The HTML would need to contain `&amp;#123;` and `&amp;#125;` instead of `&#123;` and `&#125;` or `{` and `}`.

**Comment by eduardomozart** [comment] 2024-02-08 13:49
Can you try to search for ``AOS-CX 10.12 Security Guide``?
The search result are rendered as expected:
<img width="1081" alt="image" src="https://github.com/dokuwiki/dokuwiki/assets/2974895/9dd511ef-d73b-4544-b39b-2f47b74bd311">
But when clicking the link with the search result, it's not.
I do not believe it's an extension related issue because I disabled all extensions and cleared the cache but the issue persists.

**Comment by fiwswe** [comment] 2024-02-08 14:13
> Can you try to search for `AOS-CX 10.12 Security Guide`?

Sure but as expected there were no search results. Remember that I only have a small test page containing this:
```
====== Test Issue #4192 ======

See: [[https://github.com/dokuwiki/dokuwiki/issues/4192|Character rendering issue after "Kratos" upgrade (#4192)]]

====== ArubaOS-CX ======

<code bibtex>
@Comment{refnotes,
  namespace = "harvard"
}
</code>
```

Doing the equivalent search for my test page yields this link: `https://mywikihostname/doku.php?id=text:issue_4192&s[]=arubaos`. Adding more search terms that still find my test page does not make any difference.

**Comment by fiwswe** [comment] 2024-02-08 15:24
So at some point the braces are converted to HTML entities. Then the search finds parts of the entity and the search results URL highlights these parts, breaking the entity, to the innocuous HTML string `&#<span class="search_hit">12</span>3;` which is no longer an entity.

I have no idea where to even start to fix this ;-)

**Comment by Klap-in** [comment] 2024-02-08 15:56
Highlighting is happening here:
https://github.com/dokuwiki/dokuwiki/blob/ab86a1cdff274f08d0d99df074557be85357331c/inc/html.php#L287-L315

**Comment by eduardomozart** [comment] 2024-02-08 16:03
I created the https://github.com/dokuwiki/dokuwiki/pull/4196 that seems to fix this issue.

**Comment by splitbrain** [comment] 2024-02-09 10:28
There is simply no easy fix for this problem. It has been discussed before in #3694: html_hilight() tries basically tries to modify HTML with regex and as we all know, this is futile.

Since this is not as initially assumed a regression, I will close this as a duplicate. The proper way to fix this is to get rid of html_hilight and do the highlighting in the frontend where the browser's DOM parser can be utilized.

**Closed by splitbrain** 2024-02-09 10:28 UTC
