### ISSUE TITLE
feed.php doesn't work anymore

### ISSUE THREAD

**Issue by cardi-m** [dokuwiki/dokuwiki#4208] opened 2024-02-12 11:04 UTC
I had the following code on my startpage to show the latest changes. 
`{{rss>https://example.exm/feed.php?linkto=current&content=abstract&type=rss2&mode=recent&num=10&minor=1&only_new=0}}`

Since the update to Release **2024-02-06 "Kaos"** i get an Error that the feed can not be loaded. When i try it directly my bowser download a *.php with the content.

I read in the Changelog that the feedgeneration has changed, but i doen't check what i have to chnage.

**Comment by splitbrain** [comment] 2024-02-12 12:07
duplicate of #4203

**Closed by splitbrain** 2024-02-12 12:07 UTC
Labels: duplicate
