### ISSUE TITLE
TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Doku_Renderer_metadata does not have a method "table_align"

### ISSUE THREAD

**Issue by wzhik** [dokuwiki/dokuwiki#4201] opened 2024-02-10 08:31 UTC
Error:
![2024-02-10_11-23-43](https://github.com/dokuwiki/dokuwiki/assets/2204333/90906e2f-690c-475b-afe3-51104e23df87)
  
When trying to create a page with such content:
```
====== Рецепт Цельнозерновой молочный ======

^Ингредиенты   ^на 1000 гр   ^на 750 гр   ^на 500 гр 
|Мука цельн. |             | 300 гр     |            |
|Мука пшен.  |             | 100 гр     |            |
|Вода        |             | 220 гр     |            |
|Соль        |             | 1 ч/л      |            |
|Молоко      |             | 70 гр      |            |
|Дрожжи сух. |             | 1,5 ч/л    |            |
|Масло раст. |             | 15 гр      |            |
|Семечки обж.|             | 40 гр      |            |
```

Log file:
[2024-02-10.log](https://github.com/dokuwiki/dokuwiki/files/14228620/2024-02-10.log)

**Comment by Klap-in** [comment] 2024-02-10 08:40
This looks as a duplicate of https://github.com/dokuwiki/dokuwiki/issues/4186

**Closed** 2024-02-10 09:34 UTC
